var insults = [
  "You are not worth another word, else I'd call you knave.",
  "I do desire we may be better strangers.",
  "He is deformed, crooked, old and sere, \nIll-faced, worse bodied, shapeless everywhere;\nVicious, ungentle, foolish, blunt, unkind; \nStigmatical in making, worse in mind. ",
  "Thou whoreson, senseless villain!",
  "Dissembling harlot, thou art false in all!",
  "You abilities are too infant-like for doing much alone.",
  "They lie deadly that tell you you have good faces .",
  "You wear out a good wholesome forenoon in hearing a cause between an orange wife and a fosset-seller. ",
  "More of your conversation would infect my brain.",
  "For such things as you, I can scarce think there's any, ye're so slight.",
  "The tartness of his face sours ripe grapes.",
  "There is no more mercy in him than there is milk in a male tiger.",
  "Away! Thou'rt poison to my blood.",
  "O thou vile one!",
  "You had measured how long a fool you were upon the ground.",
  "Frailty, thy name is woman!",
  "They have a plentiful lack of wit.",
  "Take you me for a sponge?",
  "Here, thou incestuous, murderous, damned Dane,\nDrink off this potion!",
  "Thou hast the most unsavoury similes.",
  "This sanguine coward, this bed-presser, this horseback-breaker, this huge hill of flesh!",
  "'Sblood, you starveling, you elf-skin, you dried neat's tongue, you bull's pizzle, you stock-fish! O for breath to utter what is like thee! you tailor's-yard, you sheath, you bowcase; you vile standing-tuck! ",
  "There’s no more faith in thee than in a stewed prune.",
  "Hang him, swaggering rascal!",
  "I scorn you, scurvy companion.",
  "Away, you mouldy rogue, away!",
  "Away, you cut-purse rascal! you filthy bung, away! By this wine, I'll thrust my knife in your mouldy chaps, an you play the saucy cuttle with me. Away, you bottle-ale rascal! you basket-hilt stale juggler, you! ",
  "O braggart vile and damned furious wight!",
  "Avaunt, you cullions!",
  "Such antics do not amount to a man.",
  "He is white-livered and red-faced.",
  "They were devils incarnate.",
  "They are hare-brain'd slaves.",
  "Hag of all despite! ",
  "Take her away; for she hath lived too long, \nTo fill the world with vicious qualities. ",
  "I had rather chop this hand off at a blow,\nAnd with the other fling it at thy face.",
  "Thou mis-shapen dick!",
  "Teeth hadst thou in thy head when thou wast born, \nTo signify thou camest to bite the world. ",
  "I can see his pride \nPeep through each part of him.",
  "No man's pie is freed \nFrom his ambitious finger.",
  "You are strangely troublesome.",
  "You blocks, you stones, you worse than senseless things!",
  "A knave; a rascal; an eater of broken meats; base, proud, shallow, beggarly, three-suited, hundred-pound, filthy, worsted-stocking knave; a lily-livered, action-taking knave, a whoreson, glass-gazing, super-serviceable finical rogue; one-trunk-inheriting slave; one that wouldst be a bawd, in way of good service, and art nothing but the composition of a knave, beggar, coward, pandar, and the son and heir of a mongrel bitch: one whom I will beat into clamorous whining, if thou deniest the least syllable of thy addition.",
  "Thou whoreson zed! thou unnecessary letter!",
  "Out, dunghill!",
  "O you beast! \nI'll so maul you and your toasting-iron, \nThat you shall think the devil is come from hell.",
  "You are a tedious fool.",
  "O faithless coward! O dishonest wretch! \nWilt thou be made a man out of my vice? ",
  "Some report a sea-maid spawn’d him; some that he was begot between two stock-fishes. But it is certain that when he makes water his urine is congealed ice.",
  "A very scurvy fellow. ",
  "Thou art a Castilian King urinal!",
  "Vile worm, thou wast o’erlook’d even in thy birth.",
  "You juggler! you canker-blossom!",
  "I wonder that you will still be talking. Nobody marks you.",
  "My cousin's a fool, and thou art another.",
  "Men from children nothing differ.",
  "Heaven truly knows that thou art false as hell.",
  "Thy food is such\nAs hath been belch'd on by infected lungs.",
  "Thou lump of foul deformity!",
  "Thou unfit for any place but hell.",
  "Out of my sight! thou dost infect my eyes.",
  "A knot you are of damned bloodsuckers.",
  "You peasant swain! You whoreson malt-horse drudge!",
  "I shall laugh myself to death at this puppy-headed \nmonster!",
  "Why, thou deboshed fish thou...Wilt thou tell a monstrous lie, being but half a fish and half a monster? ",
  "Why, this hath not a finger's dignity.",
  "Thou bitch-wolf's son!",
  "I think thy horse will sooner con an oration than \nthou learn a prayer without book.",
  "Thou sodden-witted lord! thou hast no more brain than I have in mine elbows.",
  "A fusty nut with no kernel.",
  "Go hang yourself, you naughty mocking uncle!"
];

module.exports = {
  random: function() {
    return insults[Math.floor(Math.random() * insults.length)];
  }
}

